### ISSUE TITLE
Migration from Jets 1.9 to 2.1.4

### ISSUE THREAD

**Issue by noelrocha** [tongueroo/jets#362]
After migrating from Jets 1.9 to 2.1.4, when I try to deploy to production I get the follow output:

```
  ~/Workspace/dev/iugu-slackbot     master   1  bundle exec jets deploy production                                                                   1 ↵  2445  14:34:16 
bundler: failed to load command: jets (/Users/noelrocha/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bin/jets)
NoMethodError: undefined method `config' for nil:NilClass
  /Users/noelrocha/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/jets-2.1.4/lib/jets/booter.rb:80:in `connect_db'
  /Users/noelrocha/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/jets-2.1.4/lib/jets/booter.rb:69:in `setup_db'
  /Users/noelrocha/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/jets-2.1.4/lib/jets/booter.rb:26:in `boot!'
  /Users/noelrocha/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/jets-2.1.4/lib/jets/core.rb:18:in `boot'
  /Users/noelrocha/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/jets-2.1.4/lib/jets/cli.rb:46:in `boot_jets'
  /Users/noelrocha/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/jets-2.1.4/lib/jets/cli.rb:25:in `start'
  /Users/noelrocha/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/jets-2.1.4/lib/jets/cli.rb:5:in `start'
  /Users/noelrocha/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/jets-2.1.4/exe/jets:14:in `<top (required)>'
  /Users/noelrocha/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bin/jets:23:in `load'
  /Users/noelrocha/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bin/jets:23:in `<top (required)>'
```

**Comment by tongueroo** [comment]
The error stack trace leads to this line:

https://github.com/tongueroo/jets/blob/40d96d1f/lib/jets/booter.rb#L80

For some reason a primary database configuration is not being found. Dug into this a bit. Took a few guesses to what could be going on but am unsure.

Think an example project to reproduce the issue would be useful. Wondering if it's something with your database.yml.

In terms of why this happens in v2.1.x vs 1.9.x.  In 2.1.x, Jets was upgraded to use Rails 6 dependencies. This includes activerecord 6.x.  ActiveRecord changed the way configurations work to account for multiple database. So it has something to do with that but haven't been able to reproduce.

Closing out until more details are provided to reproduce.
